matrix:
  include:
    - rvm: 1.8.7
      gemfile: gemfiles/Gemfile.net_http_mime-types
    - rvm: 1.8.7
      gemfile: gemfiles/Gemfile.typhoeus_mime-types
    - rvm: 1.9.2
      gemfile: gemfiles/Gemfile.net_http
    - rvm: 1.9.2
      gemfile: gemfiles/Gemfile.typhoeus
    - rvm: 1.9.3
      gemfile: gemfiles/Gemfile.net_http
    - rvm: 1.9.3
      gemfile: gemfiles/Gemfile.typhoeus
    - rvm: jruby
      gemfile: gemfiles/Gemfile.net_http
    - rvm: jruby
      gemfile: gemfiles/Gemfile.typhoeus
    - rvm: ree
      gemfile: gemfiles/Gemfile.net_http_mime-types
    - rvm: ree
      gemfile: gemfiles/Gemfile.typhoeus_mime-types
install: bundle install --without developer
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/edaa9e7b8d7812636188
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: true      # default: false